### ISSUE TITLE
Django 1.8 compat release?

### ISSUE THREAD

**Issue by giftig** [disqus/gargoyle#101]
I ran into a compatibility issue with Django 1.8, but after poking around a bit, I notice the head of this project has fixed it. The last release of gargoyle is 0.11.0 though, which doesn't include that fix. Any chance of a new release? I'd like to be able to manage this dependency with pip properly.

**Comment by jlward** [comment]
+1

**Comment by adamchainz** [comment]
The YPlan fork is being kept up to date: https://github.com/YPlan/gargoyle and is available with `pip install gargoyle-yplan`.
