### ISSUE TITLE
add info about django 1.6

### ISSUE THREAD

**Issue by ustun** [disqus/gargoyle#90]
I know that disqus is not using >1.4, but do you have user reports as to whether the library is working properly in 1.6? In my limited testing locally, I haven't run into any problems yet.

Thank you.

**Comment by mattrobenolt** [comment]
@frewsxcv might have some information. :)

**Comment by frewsxcv** [comment]
We've been running 0.10.9 on production with Django 1.6 for a while and haven't had any issues. Django 1.7 support should land very soon hopefully ;)

**Comment by ustun** [comment]
We have been running on 1.6 without any issues as well.

**Comment by frewsxcv** [comment]
This can probably be closed then. A new version of gargoyle was released yesterday
